apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: dotnet-app-build

on:
  push:
    branches:
      - '**'  # Replace with the branch you want to trigger the build and deploy from
jobs:
  custom-job:
    delegates: ./customjobs/custom-job.yml
    with:
      customjob_input1: provided job input1
  custom-job1:
    delegates: ./customjobs/custom-job.yml
    with:
      customjob_input1: provided job input1
  custom-job2:
    delegates: ./customjobs/custom-job.yml
    with:
      customjob_input1: provided job input1
  custom-job3:
    delegates: ./customjobs/custom-job.yml
    with:
      customjob_input1: provided job input1
  custom-job4:
    delegates: ./customjobs/custom-job.yml
    with:
      customjob_input1: provided job input1
