name: Reusable workflow example with env secret

on:
  workflow_call:
    inputs:
      config-path:
        required: true
        type: string
jobs:
  triage:
    environment: staging
    runs-on: ubuntu-latest
    steps:
    - run: echo ${{inputs.config-path}}
      shell: bash
    - run: echo ${{ secrets.SECRET1 }}
      shell: bash
